---
# See https://docs.ansible.com/ansible/latest/dev_guide/collections_galaxy_meta.html

namespace: heatmiser
name: ansible_snapshot
version: 1.0.0
readme: README.md
authors:
  - Mike Savage (github.com/heatmiser)
description: Ansible collection for snapshots/reversion for all types of systems, infra, and cloud
license_file: LICENSE
tags:
  # tags so people can search for collections https://galaxy.ansible.com/search
  # tags are all lower-case, no spaces, no dashes.
  - snapshot
  - snapshots
  - backup
  - tools
repository: https://github.com/heatmiser/ansible-snapshot
# documentation: https://github.com/ansible-collection-migration/community.REPO_NAME/tree/main/docs
homepage: https://github.com/heatmiser/ansible-snapshot
issues: https://github.com/heatmiser/ansible-snapshot/issues
build_ignore:
  # https://docs.ansible.com/ansible/devel/dev_guide/developing_collections_distributing.html#ignoring-files-and-folders
  - .gitignore
  - changelogs/.plugin-cache.yaml
dependencies:
  "ansible.posix": ">=1.5.1"
  "community.general": '>=6.6.0'
...
