---
- name: Display ec2_instance_action
  ansible.builtin.debug:
    var: ec2_instance_action
    verbosity: 3

# Gather info
- name: Get instance details
  ansible.builtin.include_tasks: instance/get_instance_details.yml
  when: |
    ec2_instance_action == "start" or
    ec2_instance_action == "stop" or
    ec2_instance_action == "snapshot_create" or
    ec2_instance_action == "snapshot_revert"

# Actions
- name: Start instance
  ansible.builtin.include_tasks: instance/start_instances.yml
  when: ec2_instance_action == "start"

- name: Stop instance
  ansible.builtin.include_tasks: instance/stop_instances.yml
  when: ec2_instance_action == "stop"

- name: Create instance snapshot
  delegate_to: localhost
  when: ec2_instance_action == "snapshot_create"
  block:
    - name: Stop instance
      ansible.builtin.include_tasks: instance/stop_instances.yml
      when: ec2_stop_instance_for_snapshot | default(true)
    - name: Create snapshot
      ansible.builtin.include_tasks: snapshot/snapshot_create.yml
    - name: Start instance
      ansible.builtin.include_tasks: instance/start_instances.yml
      when: ec2_stop_instance_for_snapshot | default(true)

- name: Delete instance snapshot
  ansible.builtin.include_tasks: snapshot/snapshot_delete.yml
  when: ec2_instance_action == "snapshot_delete"

- name: Revert instance snapshot
  delegate_to: localhost
  when: ec2_instance_action == "snapshot_revert"
  block:
    - name: Get snapshot details
      ansible.builtin.include_tasks: snapshot/get_snapshot_details.yml
    - name: Stop instance
      ansible.builtin.include_tasks: instance/stop_instances.yml
    - name: Detach EBS volume
      ansible.builtin.include_tasks: instance/detach_volume.yml
    - name: Create new EBS volume from snapshot and attach to instance
      ansible.builtin.include_tasks: instance/new_volume_and_attach.yml
    - name: Delete prior EBS volume
      when: delete_prior_volume
      ansible.builtin.include_tasks: instance/delete_volume.yml
    - name: Start instance
      ansible.builtin.include_tasks: instance/start_instances.yml

- name: Display instance snapshot details
  ansible.builtin.include_tasks: snapshot/get_snapshot_details.yml
  when: ec2_instance_action == "get_snapshot_details"
...
